import type { Connector, CreateConnector } from '@logto/schemas';
/**
 * We are using `id` and `connectorFactoryId` here:
 *
 * - `id` is used to identify connectors from the database.
 * - `connectorFactoryId` is used to identify connectors - more specifically, connector factories - in packages/connectors
 * that contain metadata (considered connectors' FIXED properties) and code implementation (which determines how connectors work).
 */
export declare const listConnectors: () => Promise<{
    isStandard?: boolean | undefined;
    configTemplate?: string | undefined;
    formItems?: ({
        placeholder?: string | undefined;
        required?: boolean | undefined;
        defaultValue?: unknown;
        showConditions?: {
            expectValue?: unknown;
            targetKey: string;
        }[] | undefined;
        description?: string | undefined;
        tooltip?: string | undefined;
        isConfidential?: boolean | undefined;
        type: import("@logto/connector-kit").ConnectorConfigFormItemType.Select;
        selectItems: {
            value: string;
            title: string;
        }[];
        key: string;
        label: string;
    } | {
        placeholder?: string | undefined;
        required?: boolean | undefined;
        defaultValue?: unknown;
        showConditions?: {
            expectValue?: unknown;
            targetKey: string;
        }[] | undefined;
        description?: string | undefined;
        tooltip?: string | undefined;
        isConfidential?: boolean | undefined;
        type: import("@logto/connector-kit").ConnectorConfigFormItemType.Text | import("@logto/connector-kit").ConnectorConfigFormItemType.Number | import("@logto/connector-kit").ConnectorConfigFormItemType.MultilineText | import("@logto/connector-kit").ConnectorConfigFormItemType.Switch | import("@logto/connector-kit").ConnectorConfigFormItemType.Json;
        key: string;
        label: string;
    })[] | undefined;
    isDemo?: boolean | undefined;
    extraInfo?: Record<string, unknown> | undefined;
    usage?: number | undefined;
    type: import("@logto/schemas").ConnectorType;
    id: string;
    name: {
        en: string;
    } & {
        "af-ZA"?: string | undefined;
        "am-ET"?: string | undefined;
        "ar-AR"?: string | undefined;
        "as-IN"?: string | undefined;
        "az-AZ"?: string | undefined;
        "be-BY"?: string | undefined;
        "bg-BG"?: string | undefined;
        "bn-IN"?: string | undefined;
        "br-FR"?: string | undefined;
        "bs-BA"?: string | undefined;
        "ca-ES"?: string | undefined;
        "cb-IQ"?: string | undefined;
        "co-FR"?: string | undefined;
        "cs-CZ"?: string | undefined;
        "cx-PH"?: string | undefined;
        "cy-GB"?: string | undefined;
        "da-DK"?: string | undefined;
        de?: string | undefined;
        "de-DE"?: string | undefined;
        "el-GR"?: string | undefined;
        "en-GB"?: string | undefined;
        "en-US"?: string | undefined;
        "eo-EO"?: string | undefined;
        es?: string | undefined;
        "es-ES"?: string | undefined;
        "es-419"?: string | undefined;
        "et-EE"?: string | undefined;
        "eu-ES"?: string | undefined;
        "fa-IR"?: string | undefined;
        "ff-NG"?: string | undefined;
        "fi-FI"?: string | undefined;
        "fo-FO"?: string | undefined;
        fr?: string | undefined;
        "fr-CA"?: string | undefined;
        "fr-FR"?: string | undefined;
        "fy-NL"?: string | undefined;
        "ga-IE"?: string | undefined;
        "gl-ES"?: string | undefined;
        "gn-PY"?: string | undefined;
        "gu-IN"?: string | undefined;
        "ha-NG"?: string | undefined;
        "he-IL"?: string | undefined;
        "hi-IN"?: string | undefined;
        "hr-HR"?: string | undefined;
        "ht-HT"?: string | undefined;
        "hu-HU"?: string | undefined;
        "hy-AM"?: string | undefined;
        "id-ID"?: string | undefined;
        "ik-US"?: string | undefined;
        "is-IS"?: string | undefined;
        it?: string | undefined;
        "it-IT"?: string | undefined;
        "iu-CA"?: string | undefined;
        ja?: string | undefined;
        "ja-JP"?: string | undefined;
        "ja-KS"?: string | undefined;
        "jv-ID"?: string | undefined;
        "ka-GE"?: string | undefined;
        "kk-KZ"?: string | undefined;
        "km-KH"?: string | undefined;
        "kn-IN"?: string | undefined;
        ko?: string | undefined;
        "ko-KR"?: string | undefined;
        "ku-TR"?: string | undefined;
        "ky-KG"?: string | undefined;
        "lo-LA"?: string | undefined;
        "lt-LT"?: string | undefined;
        "lv-LV"?: string | undefined;
        "mg-MG"?: string | undefined;
        "mk-MK"?: string | undefined;
        "ml-IN"?: string | undefined;
        "mn-MN"?: string | undefined;
        "mr-IN"?: string | undefined;
        "ms-MY"?: string | undefined;
        "mt-MT"?: string | undefined;
        "my-MM"?: string | undefined;
        "nb-NO"?: string | undefined;
        "ne-NP"?: string | undefined;
        "nl-BE"?: string | undefined;
        "nl-NL"?: string | undefined;
        "nn-NO"?: string | undefined;
        "or-IN"?: string | undefined;
        "pa-IN"?: string | undefined;
        "pl-PL"?: string | undefined;
        "ps-AF"?: string | undefined;
        pt?: string | undefined;
        "pt-BR"?: string | undefined;
        "pt-PT"?: string | undefined;
        "ro-RO"?: string | undefined;
        ru?: string | undefined;
        "ru-RU"?: string | undefined;
        "rw-RW"?: string | undefined;
        "sc-IT"?: string | undefined;
        "si-LK"?: string | undefined;
        "sk-SK"?: string | undefined;
        "sl-SI"?: string | undefined;
        "sn-ZW"?: string | undefined;
        "sq-AL"?: string | undefined;
        "sr-RS"?: string | undefined;
        "sv-SE"?: string | undefined;
        "sw-KE"?: string | undefined;
        "sy-SY"?: string | undefined;
        "sz-PL"?: string | undefined;
        "ta-IN"?: string | undefined;
        "te-IN"?: string | undefined;
        "tg-TJ"?: string | undefined;
        "th-TH"?: string | undefined;
        "tl-PH"?: string | undefined;
        tr?: string | undefined;
        "tr-TR"?: string | undefined;
        "tt-RU"?: string | undefined;
        "tz-MA"?: string | undefined;
        "uk-UA"?: string | undefined;
        "ur-PK"?: string | undefined;
        "uz-UZ"?: string | undefined;
        "vi-VN"?: string | undefined;
        zh?: string | undefined;
        "zh-CN"?: string | undefined;
        "zh-HK"?: string | undefined;
        "zh-MO"?: string | undefined;
        "zh-TW"?: string | undefined;
        "zz-TR"?: string | undefined;
    };
    description: {
        en: string;
    } & {
        "af-ZA"?: string | undefined;
        "am-ET"?: string | undefined;
        "ar-AR"?: string | undefined;
        "as-IN"?: string | undefined;
        "az-AZ"?: string | undefined;
        "be-BY"?: string | undefined;
        "bg-BG"?: string | undefined;
        "bn-IN"?: string | undefined;
        "br-FR"?: string | undefined;
        "bs-BA"?: string | undefined;
        "ca-ES"?: string | undefined;
        "cb-IQ"?: string | undefined;
        "co-FR"?: string | undefined;
        "cs-CZ"?: string | undefined;
        "cx-PH"?: string | undefined;
        "cy-GB"?: string | undefined;
        "da-DK"?: string | undefined;
        de?: string | undefined;
        "de-DE"?: string | undefined;
        "el-GR"?: string | undefined;
        "en-GB"?: string | undefined;
        "en-US"?: string | undefined;
        "eo-EO"?: string | undefined;
        es?: string | undefined;
        "es-ES"?: string | undefined;
        "es-419"?: string | undefined;
        "et-EE"?: string | undefined;
        "eu-ES"?: string | undefined;
        "fa-IR"?: string | undefined;
        "ff-NG"?: string | undefined;
        "fi-FI"?: string | undefined;
        "fo-FO"?: string | undefined;
        fr?: string | undefined;
        "fr-CA"?: string | undefined;
        "fr-FR"?: string | undefined;
        "fy-NL"?: string | undefined;
        "ga-IE"?: string | undefined;
        "gl-ES"?: string | undefined;
        "gn-PY"?: string | undefined;
        "gu-IN"?: string | undefined;
        "ha-NG"?: string | undefined;
        "he-IL"?: string | undefined;
        "hi-IN"?: string | undefined;
        "hr-HR"?: string | undefined;
        "ht-HT"?: string | undefined;
        "hu-HU"?: string | undefined;
        "hy-AM"?: string | undefined;
        "id-ID"?: string | undefined;
        "ik-US"?: string | undefined;
        "is-IS"?: string | undefined;
        it?: string | undefined;
        "it-IT"?: string | undefined;
        "iu-CA"?: string | undefined;
        ja?: string | undefined;
        "ja-JP"?: string | undefined;
        "ja-KS"?: string | undefined;
        "jv-ID"?: string | undefined;
        "ka-GE"?: string | undefined;
        "kk-KZ"?: string | undefined;
        "km-KH"?: string | undefined;
        "kn-IN"?: string | undefined;
        ko?: string | undefined;
        "ko-KR"?: string | undefined;
        "ku-TR"?: string | undefined;
        "ky-KG"?: string | undefined;
        "lo-LA"?: string | undefined;
        "lt-LT"?: string | undefined;
        "lv-LV"?: string | undefined;
        "mg-MG"?: string | undefined;
        "mk-MK"?: string | undefined;
        "ml-IN"?: string | undefined;
        "mn-MN"?: string | undefined;
        "mr-IN"?: string | undefined;
        "ms-MY"?: string | undefined;
        "mt-MT"?: string | undefined;
        "my-MM"?: string | undefined;
        "nb-NO"?: string | undefined;
        "ne-NP"?: string | undefined;
        "nl-BE"?: string | undefined;
        "nl-NL"?: string | undefined;
        "nn-NO"?: string | undefined;
        "or-IN"?: string | undefined;
        "pa-IN"?: string | undefined;
        "pl-PL"?: string | undefined;
        "ps-AF"?: string | undefined;
        pt?: string | undefined;
        "pt-BR"?: string | undefined;
        "pt-PT"?: string | undefined;
        "ro-RO"?: string | undefined;
        ru?: string | undefined;
        "ru-RU"?: string | undefined;
        "rw-RW"?: string | undefined;
        "sc-IT"?: string | undefined;
        "si-LK"?: string | undefined;
        "sk-SK"?: string | undefined;
        "sl-SI"?: string | undefined;
        "sn-ZW"?: string | undefined;
        "sq-AL"?: string | undefined;
        "sr-RS"?: string | undefined;
        "sv-SE"?: string | undefined;
        "sw-KE"?: string | undefined;
        "sy-SY"?: string | undefined;
        "sz-PL"?: string | undefined;
        "ta-IN"?: string | undefined;
        "te-IN"?: string | undefined;
        "tg-TJ"?: string | undefined;
        "th-TH"?: string | undefined;
        "tl-PH"?: string | undefined;
        tr?: string | undefined;
        "tr-TR"?: string | undefined;
        "tt-RU"?: string | undefined;
        "tz-MA"?: string | undefined;
        "uk-UA"?: string | undefined;
        "ur-PK"?: string | undefined;
        "uz-UZ"?: string | undefined;
        "vi-VN"?: string | undefined;
        zh?: string | undefined;
        "zh-CN"?: string | undefined;
        "zh-HK"?: string | undefined;
        "zh-MO"?: string | undefined;
        "zh-TW"?: string | undefined;
        "zz-TR"?: string | undefined;
    };
    syncProfile: boolean;
    connectorId: string;
    config: import("@logto/schemas").JsonObject;
    metadata: {
        [x: string]: unknown;
        target?: string | undefined;
        name?: ({
            en: string;
        } & {
            "af-ZA"?: string | undefined;
            "am-ET"?: string | undefined;
            "ar-AR"?: string | undefined;
            "as-IN"?: string | undefined;
            "az-AZ"?: string | undefined;
            "be-BY"?: string | undefined;
            "bg-BG"?: string | undefined;
            "bn-IN"?: string | undefined;
            "br-FR"?: string | undefined;
            "bs-BA"?: string | undefined;
            "ca-ES"?: string | undefined;
            "cb-IQ"?: string | undefined;
            "co-FR"?: string | undefined;
            "cs-CZ"?: string | undefined;
            "cx-PH"?: string | undefined;
            "cy-GB"?: string | undefined;
            "da-DK"?: string | undefined;
            de?: string | undefined;
            "de-DE"?: string | undefined;
            "el-GR"?: string | undefined;
            "en-GB"?: string | undefined;
            "en-US"?: string | undefined;
            "eo-EO"?: string | undefined;
            es?: string | undefined;
            "es-ES"?: string | undefined;
            "es-419"?: string | undefined;
            "et-EE"?: string | undefined;
            "eu-ES"?: string | undefined;
            "fa-IR"?: string | undefined;
            "ff-NG"?: string | undefined;
            "fi-FI"?: string | undefined;
            "fo-FO"?: string | undefined;
            fr?: string | undefined;
            "fr-CA"?: string | undefined;
            "fr-FR"?: string | undefined;
            "fy-NL"?: string | undefined;
            "ga-IE"?: string | undefined;
            "gl-ES"?: string | undefined;
            "gn-PY"?: string | undefined;
            "gu-IN"?: string | undefined;
            "ha-NG"?: string | undefined;
            "he-IL"?: string | undefined;
            "hi-IN"?: string | undefined;
            "hr-HR"?: string | undefined;
            "ht-HT"?: string | undefined;
            "hu-HU"?: string | undefined;
            "hy-AM"?: string | undefined;
            "id-ID"?: string | undefined;
            "ik-US"?: string | undefined;
            "is-IS"?: string | undefined;
            it?: string | undefined;
            "it-IT"?: string | undefined;
            "iu-CA"?: string | undefined;
            ja?: string | undefined;
            "ja-JP"?: string | undefined;
            "ja-KS"?: string | undefined;
            "jv-ID"?: string | undefined;
            "ka-GE"?: string | undefined;
            "kk-KZ"?: string | undefined;
            "km-KH"?: string | undefined;
            "kn-IN"?: string | undefined;
            ko?: string | undefined;
            "ko-KR"?: string | undefined;
            "ku-TR"?: string | undefined;
            "ky-KG"?: string | undefined;
            "lo-LA"?: string | undefined;
            "lt-LT"?: string | undefined;
            "lv-LV"?: string | undefined;
            "mg-MG"?: string | undefined;
            "mk-MK"?: string | undefined;
            "ml-IN"?: string | undefined;
            "mn-MN"?: string | undefined;
            "mr-IN"?: string | undefined;
            "ms-MY"?: string | undefined;
            "mt-MT"?: string | undefined;
            "my-MM"?: string | undefined;
            "nb-NO"?: string | undefined;
            "ne-NP"?: string | undefined;
            "nl-BE"?: string | undefined;
            "nl-NL"?: string | undefined;
            "nn-NO"?: string | undefined;
            "or-IN"?: string | undefined;
            "pa-IN"?: string | undefined;
            "pl-PL"?: string | undefined;
            "ps-AF"?: string | undefined;
            pt?: string | undefined;
            "pt-BR"?: string | undefined;
            "pt-PT"?: string | undefined;
            "ro-RO"?: string | undefined;
            ru?: string | undefined;
            "ru-RU"?: string | undefined;
            "rw-RW"?: string | undefined;
            "sc-IT"?: string | undefined;
            "si-LK"?: string | undefined;
            "sk-SK"?: string | undefined;
            "sl-SI"?: string | undefined;
            "sn-ZW"?: string | undefined;
            "sq-AL"?: string | undefined;
            "sr-RS"?: string | undefined;
            "sv-SE"?: string | undefined;
            "sw-KE"?: string | undefined;
            "sy-SY"?: string | undefined;
            "sz-PL"?: string | undefined;
            "ta-IN"?: string | undefined;
            "te-IN"?: string | undefined;
            "tg-TJ"?: string | undefined;
            "th-TH"?: string | undefined;
            "tl-PH"?: string | undefined;
            tr?: string | undefined;
            "tr-TR"?: string | undefined;
            "tt-RU"?: string | undefined;
            "tz-MA"?: string | undefined;
            "uk-UA"?: string | undefined;
            "ur-PK"?: string | undefined;
            "uz-UZ"?: string | undefined;
            "vi-VN"?: string | undefined;
            zh?: string | undefined;
            "zh-CN"?: string | undefined;
            "zh-HK"?: string | undefined;
            "zh-MO"?: string | undefined;
            "zh-TW"?: string | undefined;
            "zz-TR"?: string | undefined;
        }) | undefined;
        logo?: string | undefined;
        logoDark?: string | null | undefined;
    };
    target: string;
    platform: import("@logto/schemas").ConnectorPlatform | null;
    logo: string;
    logoDark: string | null;
    readme: string;
}[]>;
export declare const getConnector: (id: string) => Promise<{
    isStandard?: boolean | undefined;
    configTemplate?: string | undefined;
    formItems?: ({
        placeholder?: string | undefined;
        required?: boolean | undefined;
        defaultValue?: unknown;
        showConditions?: {
            expectValue?: unknown;
            targetKey: string;
        }[] | undefined;
        description?: string | undefined;
        tooltip?: string | undefined;
        isConfidential?: boolean | undefined;
        type: import("@logto/connector-kit").ConnectorConfigFormItemType.Select;
        selectItems: {
            value: string;
            title: string;
        }[];
        key: string;
        label: string;
    } | {
        placeholder?: string | undefined;
        required?: boolean | undefined;
        defaultValue?: unknown;
        showConditions?: {
            expectValue?: unknown;
            targetKey: string;
        }[] | undefined;
        description?: string | undefined;
        tooltip?: string | undefined;
        isConfidential?: boolean | undefined;
        type: import("@logto/connector-kit").ConnectorConfigFormItemType.Text | import("@logto/connector-kit").ConnectorConfigFormItemType.Number | import("@logto/connector-kit").ConnectorConfigFormItemType.MultilineText | import("@logto/connector-kit").ConnectorConfigFormItemType.Switch | import("@logto/connector-kit").ConnectorConfigFormItemType.Json;
        key: string;
        label: string;
    })[] | undefined;
    isDemo?: boolean | undefined;
    extraInfo?: Record<string, unknown> | undefined;
    usage?: number | undefined;
    type: import("@logto/schemas").ConnectorType;
    id: string;
    name: {
        en: string;
    } & {
        "af-ZA"?: string | undefined;
        "am-ET"?: string | undefined;
        "ar-AR"?: string | undefined;
        "as-IN"?: string | undefined;
        "az-AZ"?: string | undefined;
        "be-BY"?: string | undefined;
        "bg-BG"?: string | undefined;
        "bn-IN"?: string | undefined;
        "br-FR"?: string | undefined;
        "bs-BA"?: string | undefined;
        "ca-ES"?: string | undefined;
        "cb-IQ"?: string | undefined;
        "co-FR"?: string | undefined;
        "cs-CZ"?: string | undefined;
        "cx-PH"?: string | undefined;
        "cy-GB"?: string | undefined;
        "da-DK"?: string | undefined;
        de?: string | undefined;
        "de-DE"?: string | undefined;
        "el-GR"?: string | undefined;
        "en-GB"?: string | undefined;
        "en-US"?: string | undefined;
        "eo-EO"?: string | undefined;
        es?: string | undefined;
        "es-ES"?: string | undefined;
        "es-419"?: string | undefined;
        "et-EE"?: string | undefined;
        "eu-ES"?: string | undefined;
        "fa-IR"?: string | undefined;
        "ff-NG"?: string | undefined;
        "fi-FI"?: string | undefined;
        "fo-FO"?: string | undefined;
        fr?: string | undefined;
        "fr-CA"?: string | undefined;
        "fr-FR"?: string | undefined;
        "fy-NL"?: string | undefined;
        "ga-IE"?: string | undefined;
        "gl-ES"?: string | undefined;
        "gn-PY"?: string | undefined;
        "gu-IN"?: string | undefined;
        "ha-NG"?: string | undefined;
        "he-IL"?: string | undefined;
        "hi-IN"?: string | undefined;
        "hr-HR"?: string | undefined;
        "ht-HT"?: string | undefined;
        "hu-HU"?: string | undefined;
        "hy-AM"?: string | undefined;
        "id-ID"?: string | undefined;
        "ik-US"?: string | undefined;
        "is-IS"?: string | undefined;
        it?: string | undefined;
        "it-IT"?: string | undefined;
        "iu-CA"?: string | undefined;
        ja?: string | undefined;
        "ja-JP"?: string | undefined;
        "ja-KS"?: string | undefined;
        "jv-ID"?: string | undefined;
        "ka-GE"?: string | undefined;
        "kk-KZ"?: string | undefined;
        "km-KH"?: string | undefined;
        "kn-IN"?: string | undefined;
        ko?: string | undefined;
        "ko-KR"?: string | undefined;
        "ku-TR"?: string | undefined;
        "ky-KG"?: string | undefined;
        "lo-LA"?: string | undefined;
        "lt-LT"?: string | undefined;
        "lv-LV"?: string | undefined;
        "mg-MG"?: string | undefined;
        "mk-MK"?: string | undefined;
        "ml-IN"?: string | undefined;
        "mn-MN"?: string | undefined;
        "mr-IN"?: string | undefined;
        "ms-MY"?: string | undefined;
        "mt-MT"?: string | undefined;
        "my-MM"?: string | undefined;
        "nb-NO"?: string | undefined;
        "ne-NP"?: string | undefined;
        "nl-BE"?: string | undefined;
        "nl-NL"?: string | undefined;
        "nn-NO"?: string | undefined;
        "or-IN"?: string | undefined;
        "pa-IN"?: string | undefined;
        "pl-PL"?: string | undefined;
        "ps-AF"?: string | undefined;
        pt?: string | undefined;
        "pt-BR"?: string | undefined;
        "pt-PT"?: string | undefined;
        "ro-RO"?: string | undefined;
        ru?: string | undefined;
        "ru-RU"?: string | undefined;
        "rw-RW"?: string | undefined;
        "sc-IT"?: string | undefined;
        "si-LK"?: string | undefined;
        "sk-SK"?: string | undefined;
        "sl-SI"?: string | undefined;
        "sn-ZW"?: string | undefined;
        "sq-AL"?: string | undefined;
        "sr-RS"?: string | undefined;
        "sv-SE"?: string | undefined;
        "sw-KE"?: string | undefined;
        "sy-SY"?: string | undefined;
        "sz-PL"?: string | undefined;
        "ta-IN"?: string | undefined;
        "te-IN"?: string | undefined;
        "tg-TJ"?: string | undefined;
        "th-TH"?: string | undefined;
        "tl-PH"?: string | undefined;
        tr?: string | undefined;
        "tr-TR"?: string | undefined;
        "tt-RU"?: string | undefined;
        "tz-MA"?: string | undefined;
        "uk-UA"?: string | undefined;
        "ur-PK"?: string | undefined;
        "uz-UZ"?: string | undefined;
        "vi-VN"?: string | undefined;
        zh?: string | undefined;
        "zh-CN"?: string | undefined;
        "zh-HK"?: string | undefined;
        "zh-MO"?: string | undefined;
        "zh-TW"?: string | undefined;
        "zz-TR"?: string | undefined;
    };
    description: {
        en: string;
    } & {
        "af-ZA"?: string | undefined;
        "am-ET"?: string | undefined;
        "ar-AR"?: string | undefined;
        "as-IN"?: string | undefined;
        "az-AZ"?: string | undefined;
        "be-BY"?: string | undefined;
        "bg-BG"?: string | undefined;
        "bn-IN"?: string | undefined;
        "br-FR"?: string | undefined;
        "bs-BA"?: string | undefined;
        "ca-ES"?: string | undefined;
        "cb-IQ"?: string | undefined;
        "co-FR"?: string | undefined;
        "cs-CZ"?: string | undefined;
        "cx-PH"?: string | undefined;
        "cy-GB"?: string | undefined;
        "da-DK"?: string | undefined;
        de?: string | undefined;
        "de-DE"?: string | undefined;
        "el-GR"?: string | undefined;
        "en-GB"?: string | undefined;
        "en-US"?: string | undefined;
        "eo-EO"?: string | undefined;
        es?: string | undefined;
        "es-ES"?: string | undefined;
        "es-419"?: string | undefined;
        "et-EE"?: string | undefined;
        "eu-ES"?: string | undefined;
        "fa-IR"?: string | undefined;
        "ff-NG"?: string | undefined;
        "fi-FI"?: string | undefined;
        "fo-FO"?: string | undefined;
        fr?: string | undefined;
        "fr-CA"?: string | undefined;
        "fr-FR"?: string | undefined;
        "fy-NL"?: string | undefined;
        "ga-IE"?: string | undefined;
        "gl-ES"?: string | undefined;
        "gn-PY"?: string | undefined;
        "gu-IN"?: string | undefined;
        "ha-NG"?: string | undefined;
        "he-IL"?: string | undefined;
        "hi-IN"?: string | undefined;
        "hr-HR"?: string | undefined;
        "ht-HT"?: string | undefined;
        "hu-HU"?: string | undefined;
        "hy-AM"?: string | undefined;
        "id-ID"?: string | undefined;
        "ik-US"?: string | undefined;
        "is-IS"?: string | undefined;
        it?: string | undefined;
        "it-IT"?: string | undefined;
        "iu-CA"?: string | undefined;
        ja?: string | undefined;
        "ja-JP"?: string | undefined;
        "ja-KS"?: string | undefined;
        "jv-ID"?: string | undefined;
        "ka-GE"?: string | undefined;
        "kk-KZ"?: string | undefined;
        "km-KH"?: string | undefined;
        "kn-IN"?: string | undefined;
        ko?: string | undefined;
        "ko-KR"?: string | undefined;
        "ku-TR"?: string | undefined;
        "ky-KG"?: string | undefined;
        "lo-LA"?: string | undefined;
        "lt-LT"?: string | undefined;
        "lv-LV"?: string | undefined;
        "mg-MG"?: string | undefined;
        "mk-MK"?: string | undefined;
        "ml-IN"?: string | undefined;
        "mn-MN"?: string | undefined;
        "mr-IN"?: string | undefined;
        "ms-MY"?: string | undefined;
        "mt-MT"?: string | undefined;
        "my-MM"?: string | undefined;
        "nb-NO"?: string | undefined;
        "ne-NP"?: string | undefined;
        "nl-BE"?: string | undefined;
        "nl-NL"?: string | undefined;
        "nn-NO"?: string | undefined;
        "or-IN"?: string | undefined;
        "pa-IN"?: string | undefined;
        "pl-PL"?: string | undefined;
        "ps-AF"?: string | undefined;
        pt?: string | undefined;
        "pt-BR"?: string | undefined;
        "pt-PT"?: string | undefined;
        "ro-RO"?: string | undefined;
        ru?: string | undefined;
        "ru-RU"?: string | undefined;
        "rw-RW"?: string | undefined;
        "sc-IT"?: string | undefined;
        "si-LK"?: string | undefined;
        "sk-SK"?: string | undefined;
        "sl-SI"?: string | undefined;
        "sn-ZW"?: string | undefined;
        "sq-AL"?: string | undefined;
        "sr-RS"?: string | undefined;
        "sv-SE"?: string | undefined;
        "sw-KE"?: string | undefined;
        "sy-SY"?: string | undefined;
        "sz-PL"?: string | undefined;
        "ta-IN"?: string | undefined;
        "te-IN"?: string | undefined;
        "tg-TJ"?: string | undefined;
        "th-TH"?: string | undefined;
        "tl-PH"?: string | undefined;
        tr?: string | undefined;
        "tr-TR"?: string | undefined;
        "tt-RU"?: string | undefined;
        "tz-MA"?: string | undefined;
        "uk-UA"?: string | undefined;
        "ur-PK"?: string | undefined;
        "uz-UZ"?: string | undefined;
        "vi-VN"?: string | undefined;
        zh?: string | undefined;
        "zh-CN"?: string | undefined;
        "zh-HK"?: string | undefined;
        "zh-MO"?: string | undefined;
        "zh-TW"?: string | undefined;
        "zz-TR"?: string | undefined;
    };
    syncProfile: boolean;
    connectorId: string;
    config: import("@logto/schemas").JsonObject;
    metadata: {
        [x: string]: unknown;
        target?: string | undefined;
        name?: ({
            en: string;
        } & {
            "af-ZA"?: string | undefined;
            "am-ET"?: string | undefined;
            "ar-AR"?: string | undefined;
            "as-IN"?: string | undefined;
            "az-AZ"?: string | undefined;
            "be-BY"?: string | undefined;
            "bg-BG"?: string | undefined;
            "bn-IN"?: string | undefined;
            "br-FR"?: string | undefined;
            "bs-BA"?: string | undefined;
            "ca-ES"?: string | undefined;
            "cb-IQ"?: string | undefined;
            "co-FR"?: string | undefined;
            "cs-CZ"?: string | undefined;
            "cx-PH"?: string | undefined;
            "cy-GB"?: string | undefined;
            "da-DK"?: string | undefined;
            de?: string | undefined;
            "de-DE"?: string | undefined;
            "el-GR"?: string | undefined;
            "en-GB"?: string | undefined;
            "en-US"?: string | undefined;
            "eo-EO"?: string | undefined;
            es?: string | undefined;
            "es-ES"?: string | undefined;
            "es-419"?: string | undefined;
            "et-EE"?: string | undefined;
            "eu-ES"?: string | undefined;
            "fa-IR"?: string | undefined;
            "ff-NG"?: string | undefined;
            "fi-FI"?: string | undefined;
            "fo-FO"?: string | undefined;
            fr?: string | undefined;
            "fr-CA"?: string | undefined;
            "fr-FR"?: string | undefined;
            "fy-NL"?: string | undefined;
            "ga-IE"?: string | undefined;
            "gl-ES"?: string | undefined;
            "gn-PY"?: string | undefined;
            "gu-IN"?: string | undefined;
            "ha-NG"?: string | undefined;
            "he-IL"?: string | undefined;
            "hi-IN"?: string | undefined;
            "hr-HR"?: string | undefined;
            "ht-HT"?: string | undefined;
            "hu-HU"?: string | undefined;
            "hy-AM"?: string | undefined;
            "id-ID"?: string | undefined;
            "ik-US"?: string | undefined;
            "is-IS"?: string | undefined;
            it?: string | undefined;
            "it-IT"?: string | undefined;
            "iu-CA"?: string | undefined;
            ja?: string | undefined;
            "ja-JP"?: string | undefined;
            "ja-KS"?: string | undefined;
            "jv-ID"?: string | undefined;
            "ka-GE"?: string | undefined;
            "kk-KZ"?: string | undefined;
            "km-KH"?: string | undefined;
            "kn-IN"?: string | undefined;
            ko?: string | undefined;
            "ko-KR"?: string | undefined;
            "ku-TR"?: string | undefined;
            "ky-KG"?: string | undefined;
            "lo-LA"?: string | undefined;
            "lt-LT"?: string | undefined;
            "lv-LV"?: string | undefined;
            "mg-MG"?: string | undefined;
            "mk-MK"?: string | undefined;
            "ml-IN"?: string | undefined;
            "mn-MN"?: string | undefined;
            "mr-IN"?: string | undefined;
            "ms-MY"?: string | undefined;
            "mt-MT"?: string | undefined;
            "my-MM"?: string | undefined;
            "nb-NO"?: string | undefined;
            "ne-NP"?: string | undefined;
            "nl-BE"?: string | undefined;
            "nl-NL"?: string | undefined;
            "nn-NO"?: string | undefined;
            "or-IN"?: string | undefined;
            "pa-IN"?: string | undefined;
            "pl-PL"?: string | undefined;
            "ps-AF"?: string | undefined;
            pt?: string | undefined;
            "pt-BR"?: string | undefined;
            "pt-PT"?: string | undefined;
            "ro-RO"?: string | undefined;
            ru?: string | undefined;
            "ru-RU"?: string | undefined;
            "rw-RW"?: string | undefined;
            "sc-IT"?: string | undefined;
            "si-LK"?: string | undefined;
            "sk-SK"?: string | undefined;
            "sl-SI"?: string | undefined;
            "sn-ZW"?: string | undefined;
            "sq-AL"?: string | undefined;
            "sr-RS"?: string | undefined;
            "sv-SE"?: string | undefined;
            "sw-KE"?: string | undefined;
            "sy-SY"?: string | undefined;
            "sz-PL"?: string | undefined;
            "ta-IN"?: string | undefined;
            "te-IN"?: string | undefined;
            "tg-TJ"?: string | undefined;
            "th-TH"?: string | undefined;
            "tl-PH"?: string | undefined;
            tr?: string | undefined;
            "tr-TR"?: string | undefined;
            "tt-RU"?: string | undefined;
            "tz-MA"?: string | undefined;
            "uk-UA"?: string | undefined;
            "ur-PK"?: string | undefined;
            "uz-UZ"?: string | undefined;
            "vi-VN"?: string | undefined;
            zh?: string | undefined;
            "zh-CN"?: string | undefined;
            "zh-HK"?: string | undefined;
            "zh-MO"?: string | undefined;
            "zh-TW"?: string | undefined;
            "zz-TR"?: string | undefined;
        }) | undefined;
        logo?: string | undefined;
        logoDark?: string | null | undefined;
    };
    target: string;
    platform: import("@logto/schemas").ConnectorPlatform | null;
    logo: string;
    logoDark: string | null;
    readme: string;
}>;
export declare const listConnectorFactories: () => Promise<{
    [x: string]: unknown;
    isStandard?: boolean | undefined;
    configTemplate?: string | undefined;
    formItems?: ({
        placeholder?: string | undefined;
        required?: boolean | undefined;
        defaultValue?: unknown;
        showConditions?: {
            expectValue?: unknown;
            targetKey: string;
        }[] | undefined;
        description?: string | undefined;
        tooltip?: string | undefined;
        isConfidential?: boolean | undefined;
        type: import("@logto/connector-kit").ConnectorConfigFormItemType.Select;
        selectItems: {
            value: string;
            title: string;
        }[];
        key: string;
        label: string;
    } | {
        placeholder?: string | undefined;
        required?: boolean | undefined;
        defaultValue?: unknown;
        showConditions?: {
            expectValue?: unknown;
            targetKey: string;
        }[] | undefined;
        description?: string | undefined;
        tooltip?: string | undefined;
        isConfidential?: boolean | undefined;
        type: import("@logto/connector-kit").ConnectorConfigFormItemType.Text | import("@logto/connector-kit").ConnectorConfigFormItemType.Number | import("@logto/connector-kit").ConnectorConfigFormItemType.MultilineText | import("@logto/connector-kit").ConnectorConfigFormItemType.Switch | import("@logto/connector-kit").ConnectorConfigFormItemType.Json;
        key: string;
        label: string;
    })[] | undefined;
    isDemo?: boolean | undefined;
    type: import("@logto/schemas").ConnectorType;
    id: string;
    name: {
        en: string;
    } & {
        "af-ZA"?: string | undefined;
        "am-ET"?: string | undefined;
        "ar-AR"?: string | undefined;
        "as-IN"?: string | undefined;
        "az-AZ"?: string | undefined;
        "be-BY"?: string | undefined;
        "bg-BG"?: string | undefined;
        "bn-IN"?: string | undefined;
        "br-FR"?: string | undefined;
        "bs-BA"?: string | undefined;
        "ca-ES"?: string | undefined;
        "cb-IQ"?: string | undefined;
        "co-FR"?: string | undefined;
        "cs-CZ"?: string | undefined;
        "cx-PH"?: string | undefined;
        "cy-GB"?: string | undefined;
        "da-DK"?: string | undefined;
        de?: string | undefined;
        "de-DE"?: string | undefined;
        "el-GR"?: string | undefined;
        "en-GB"?: string | undefined;
        "en-US"?: string | undefined;
        "eo-EO"?: string | undefined;
        es?: string | undefined;
        "es-ES"?: string | undefined;
        "es-419"?: string | undefined;
        "et-EE"?: string | undefined;
        "eu-ES"?: string | undefined;
        "fa-IR"?: string | undefined;
        "ff-NG"?: string | undefined;
        "fi-FI"?: string | undefined;
        "fo-FO"?: string | undefined;
        fr?: string | undefined;
        "fr-CA"?: string | undefined;
        "fr-FR"?: string | undefined;
        "fy-NL"?: string | undefined;
        "ga-IE"?: string | undefined;
        "gl-ES"?: string | undefined;
        "gn-PY"?: string | undefined;
        "gu-IN"?: string | undefined;
        "ha-NG"?: string | undefined;
        "he-IL"?: string | undefined;
        "hi-IN"?: string | undefined;
        "hr-HR"?: string | undefined;
        "ht-HT"?: string | undefined;
        "hu-HU"?: string | undefined;
        "hy-AM"?: string | undefined;
        "id-ID"?: string | undefined;
        "ik-US"?: string | undefined;
        "is-IS"?: string | undefined;
        it?: string | undefined;
        "it-IT"?: string | undefined;
        "iu-CA"?: string | undefined;
        ja?: string | undefined;
        "ja-JP"?: string | undefined;
        "ja-KS"?: string | undefined;
        "jv-ID"?: string | undefined;
        "ka-GE"?: string | undefined;
        "kk-KZ"?: string | undefined;
        "km-KH"?: string | undefined;
        "kn-IN"?: string | undefined;
        ko?: string | undefined;
        "ko-KR"?: string | undefined;
        "ku-TR"?: string | undefined;
        "ky-KG"?: string | undefined;
        "lo-LA"?: string | undefined;
        "lt-LT"?: string | undefined;
        "lv-LV"?: string | undefined;
        "mg-MG"?: string | undefined;
        "mk-MK"?: string | undefined;
        "ml-IN"?: string | undefined;
        "mn-MN"?: string | undefined;
        "mr-IN"?: string | undefined;
        "ms-MY"?: string | undefined;
        "mt-MT"?: string | undefined;
        "my-MM"?: string | undefined;
        "nb-NO"?: string | undefined;
        "ne-NP"?: string | undefined;
        "nl-BE"?: string | undefined;
        "nl-NL"?: string | undefined;
        "nn-NO"?: string | undefined;
        "or-IN"?: string | undefined;
        "pa-IN"?: string | undefined;
        "pl-PL"?: string | undefined;
        "ps-AF"?: string | undefined;
        pt?: string | undefined;
        "pt-BR"?: string | undefined;
        "pt-PT"?: string | undefined;
        "ro-RO"?: string | undefined;
        ru?: string | undefined;
        "ru-RU"?: string | undefined;
        "rw-RW"?: string | undefined;
        "sc-IT"?: string | undefined;
        "si-LK"?: string | undefined;
        "sk-SK"?: string | undefined;
        "sl-SI"?: string | undefined;
        "sn-ZW"?: string | undefined;
        "sq-AL"?: string | undefined;
        "sr-RS"?: string | undefined;
        "sv-SE"?: string | undefined;
        "sw-KE"?: string | undefined;
        "sy-SY"?: string | undefined;
        "sz-PL"?: string | undefined;
        "ta-IN"?: string | undefined;
        "te-IN"?: string | undefined;
        "tg-TJ"?: string | undefined;
        "th-TH"?: string | undefined;
        "tl-PH"?: string | undefined;
        tr?: string | undefined;
        "tr-TR"?: string | undefined;
        "tt-RU"?: string | undefined;
        "tz-MA"?: string | undefined;
        "uk-UA"?: string | undefined;
        "ur-PK"?: string | undefined;
        "uz-UZ"?: string | undefined;
        "vi-VN"?: string | undefined;
        zh?: string | undefined;
        "zh-CN"?: string | undefined;
        "zh-HK"?: string | undefined;
        "zh-MO"?: string | undefined;
        "zh-TW"?: string | undefined;
        "zz-TR"?: string | undefined;
    };
    description: {
        en: string;
    } & {
        "af-ZA"?: string | undefined;
        "am-ET"?: string | undefined;
        "ar-AR"?: string | undefined;
        "as-IN"?: string | undefined;
        "az-AZ"?: string | undefined;
        "be-BY"?: string | undefined;
        "bg-BG"?: string | undefined;
        "bn-IN"?: string | undefined;
        "br-FR"?: string | undefined;
        "bs-BA"?: string | undefined;
        "ca-ES"?: string | undefined;
        "cb-IQ"?: string | undefined;
        "co-FR"?: string | undefined;
        "cs-CZ"?: string | undefined;
        "cx-PH"?: string | undefined;
        "cy-GB"?: string | undefined;
        "da-DK"?: string | undefined;
        de?: string | undefined;
        "de-DE"?: string | undefined;
        "el-GR"?: string | undefined;
        "en-GB"?: string | undefined;
        "en-US"?: string | undefined;
        "eo-EO"?: string | undefined;
        es?: string | undefined;
        "es-ES"?: string | undefined;
        "es-419"?: string | undefined;
        "et-EE"?: string | undefined;
        "eu-ES"?: string | undefined;
        "fa-IR"?: string | undefined;
        "ff-NG"?: string | undefined;
        "fi-FI"?: string | undefined;
        "fo-FO"?: string | undefined;
        fr?: string | undefined;
        "fr-CA"?: string | undefined;
        "fr-FR"?: string | undefined;
        "fy-NL"?: string | undefined;
        "ga-IE"?: string | undefined;
        "gl-ES"?: string | undefined;
        "gn-PY"?: string | undefined;
        "gu-IN"?: string | undefined;
        "ha-NG"?: string | undefined;
        "he-IL"?: string | undefined;
        "hi-IN"?: string | undefined;
        "hr-HR"?: string | undefined;
        "ht-HT"?: string | undefined;
        "hu-HU"?: string | undefined;
        "hy-AM"?: string | undefined;
        "id-ID"?: string | undefined;
        "ik-US"?: string | undefined;
        "is-IS"?: string | undefined;
        it?: string | undefined;
        "it-IT"?: string | undefined;
        "iu-CA"?: string | undefined;
        ja?: string | undefined;
        "ja-JP"?: string | undefined;
        "ja-KS"?: string | undefined;
        "jv-ID"?: string | undefined;
        "ka-GE"?: string | undefined;
        "kk-KZ"?: string | undefined;
        "km-KH"?: string | undefined;
        "kn-IN"?: string | undefined;
        ko?: string | undefined;
        "ko-KR"?: string | undefined;
        "ku-TR"?: string | undefined;
        "ky-KG"?: string | undefined;
        "lo-LA"?: string | undefined;
        "lt-LT"?: string | undefined;
        "lv-LV"?: string | undefined;
        "mg-MG"?: string | undefined;
        "mk-MK"?: string | undefined;
        "ml-IN"?: string | undefined;
        "mn-MN"?: string | undefined;
        "mr-IN"?: string | undefined;
        "ms-MY"?: string | undefined;
        "mt-MT"?: string | undefined;
        "my-MM"?: string | undefined;
        "nb-NO"?: string | undefined;
        "ne-NP"?: string | undefined;
        "nl-BE"?: string | undefined;
        "nl-NL"?: string | undefined;
        "nn-NO"?: string | undefined;
        "or-IN"?: string | undefined;
        "pa-IN"?: string | undefined;
        "pl-PL"?: string | undefined;
        "ps-AF"?: string | undefined;
        pt?: string | undefined;
        "pt-BR"?: string | undefined;
        "pt-PT"?: string | undefined;
        "ro-RO"?: string | undefined;
        ru?: string | undefined;
        "ru-RU"?: string | undefined;
        "rw-RW"?: string | undefined;
        "sc-IT"?: string | undefined;
        "si-LK"?: string | undefined;
        "sk-SK"?: string | undefined;
        "sl-SI"?: string | undefined;
        "sn-ZW"?: string | undefined;
        "sq-AL"?: string | undefined;
        "sr-RS"?: string | undefined;
        "sv-SE"?: string | undefined;
        "sw-KE"?: string | undefined;
        "sy-SY"?: string | undefined;
        "sz-PL"?: string | undefined;
        "ta-IN"?: string | undefined;
        "te-IN"?: string | undefined;
        "tg-TJ"?: string | undefined;
        "th-TH"?: string | undefined;
        "tl-PH"?: string | undefined;
        tr?: string | undefined;
        "tr-TR"?: string | undefined;
        "tt-RU"?: string | undefined;
        "tz-MA"?: string | undefined;
        "uk-UA"?: string | undefined;
        "ur-PK"?: string | undefined;
        "uz-UZ"?: string | undefined;
        "vi-VN"?: string | undefined;
        zh?: string | undefined;
        "zh-CN"?: string | undefined;
        "zh-HK"?: string | undefined;
        "zh-MO"?: string | undefined;
        "zh-TW"?: string | undefined;
        "zz-TR"?: string | undefined;
    };
    target: string;
    platform: import("@logto/schemas").ConnectorPlatform | null;
    logo: string;
    logoDark: string | null;
    readme: string;
}[]>;
export declare const getConnectorFactory: (connectorFactoryId: string) => Promise<{
    [x: string]: unknown;
    isStandard?: boolean | undefined;
    configTemplate?: string | undefined;
    formItems?: ({
        placeholder?: string | undefined;
        required?: boolean | undefined;
        defaultValue?: unknown;
        showConditions?: {
            expectValue?: unknown;
            targetKey: string;
        }[] | undefined;
        description?: string | undefined;
        tooltip?: string | undefined;
        isConfidential?: boolean | undefined;
        type: import("@logto/connector-kit").ConnectorConfigFormItemType.Select;
        selectItems: {
            value: string;
            title: string;
        }[];
        key: string;
        label: string;
    } | {
        placeholder?: string | undefined;
        required?: boolean | undefined;
        defaultValue?: unknown;
        showConditions?: {
            expectValue?: unknown;
            targetKey: string;
        }[] | undefined;
        description?: string | undefined;
        tooltip?: string | undefined;
        isConfidential?: boolean | undefined;
        type: import("@logto/connector-kit").ConnectorConfigFormItemType.Text | import("@logto/connector-kit").ConnectorConfigFormItemType.Number | import("@logto/connector-kit").ConnectorConfigFormItemType.MultilineText | import("@logto/connector-kit").ConnectorConfigFormItemType.Switch | import("@logto/connector-kit").ConnectorConfigFormItemType.Json;
        key: string;
        label: string;
    })[] | undefined;
    isDemo?: boolean | undefined;
    type: import("@logto/schemas").ConnectorType;
    id: string;
    name: {
        en: string;
    } & {
        "af-ZA"?: string | undefined;
        "am-ET"?: string | undefined;
        "ar-AR"?: string | undefined;
        "as-IN"?: string | undefined;
        "az-AZ"?: string | undefined;
        "be-BY"?: string | undefined;
        "bg-BG"?: string | undefined;
        "bn-IN"?: string | undefined;
        "br-FR"?: string | undefined;
        "bs-BA"?: string | undefined;
        "ca-ES"?: string | undefined;
        "cb-IQ"?: string | undefined;
        "co-FR"?: string | undefined;
        "cs-CZ"?: string | undefined;
        "cx-PH"?: string | undefined;
        "cy-GB"?: string | undefined;
        "da-DK"?: string | undefined;
        de?: string | undefined;
        "de-DE"?: string | undefined;
        "el-GR"?: string | undefined;
        "en-GB"?: string | undefined;
        "en-US"?: string | undefined;
        "eo-EO"?: string | undefined;
        es?: string | undefined;
        "es-ES"?: string | undefined;
        "es-419"?: string | undefined;
        "et-EE"?: string | undefined;
        "eu-ES"?: string | undefined;
        "fa-IR"?: string | undefined;
        "ff-NG"?: string | undefined;
        "fi-FI"?: string | undefined;
        "fo-FO"?: string | undefined;
        fr?: string | undefined;
        "fr-CA"?: string | undefined;
        "fr-FR"?: string | undefined;
        "fy-NL"?: string | undefined;
        "ga-IE"?: string | undefined;
        "gl-ES"?: string | undefined;
        "gn-PY"?: string | undefined;
        "gu-IN"?: string | undefined;
        "ha-NG"?: string | undefined;
        "he-IL"?: string | undefined;
        "hi-IN"?: string | undefined;
        "hr-HR"?: string | undefined;
        "ht-HT"?: string | undefined;
        "hu-HU"?: string | undefined;
        "hy-AM"?: string | undefined;
        "id-ID"?: string | undefined;
        "ik-US"?: string | undefined;
        "is-IS"?: string | undefined;
        it?: string | undefined;
        "it-IT"?: string | undefined;
        "iu-CA"?: string | undefined;
        ja?: string | undefined;
        "ja-JP"?: string | undefined;
        "ja-KS"?: string | undefined;
        "jv-ID"?: string | undefined;
        "ka-GE"?: string | undefined;
        "kk-KZ"?: string | undefined;
        "km-KH"?: string | undefined;
        "kn-IN"?: string | undefined;
        ko?: string | undefined;
        "ko-KR"?: string | undefined;
        "ku-TR"?: string | undefined;
        "ky-KG"?: string | undefined;
        "lo-LA"?: string | undefined;
        "lt-LT"?: string | undefined;
        "lv-LV"?: string | undefined;
        "mg-MG"?: string | undefined;
        "mk-MK"?: string | undefined;
        "ml-IN"?: string | undefined;
        "mn-MN"?: string | undefined;
        "mr-IN"?: string | undefined;
        "ms-MY"?: string | undefined;
        "mt-MT"?: string | undefined;
        "my-MM"?: string | undefined;
        "nb-NO"?: string | undefined;
        "ne-NP"?: string | undefined;
        "nl-BE"?: string | undefined;
        "nl-NL"?: string | undefined;
        "nn-NO"?: string | undefined;
        "or-IN"?: string | undefined;
        "pa-IN"?: string | undefined;
        "pl-PL"?: string | undefined;
        "ps-AF"?: string | undefined;
        pt?: string | undefined;
        "pt-BR"?: string | undefined;
        "pt-PT"?: string | undefined;
        "ro-RO"?: string | undefined;
        ru?: string | undefined;
        "ru-RU"?: string | undefined;
        "rw-RW"?: string | undefined;
        "sc-IT"?: string | undefined;
        "si-LK"?: string | undefined;
        "sk-SK"?: string | undefined;
        "sl-SI"?: string | undefined;
        "sn-ZW"?: string | undefined;
        "sq-AL"?: string | undefined;
        "sr-RS"?: string | undefined;
        "sv-SE"?: string | undefined;
        "sw-KE"?: string | undefined;
        "sy-SY"?: string | undefined;
        "sz-PL"?: string | undefined;
        "ta-IN"?: string | undefined;
        "te-IN"?: string | undefined;
        "tg-TJ"?: string | undefined;
        "th-TH"?: string | undefined;
        "tl-PH"?: string | undefined;
        tr?: string | undefined;
        "tr-TR"?: string | undefined;
        "tt-RU"?: string | undefined;
        "tz-MA"?: string | undefined;
        "uk-UA"?: string | undefined;
        "ur-PK"?: string | undefined;
        "uz-UZ"?: string | undefined;
        "vi-VN"?: string | undefined;
        zh?: string | undefined;
        "zh-CN"?: string | undefined;
        "zh-HK"?: string | undefined;
        "zh-MO"?: string | undefined;
        "zh-TW"?: string | undefined;
        "zz-TR"?: string | undefined;
    };
    description: {
        en: string;
    } & {
        "af-ZA"?: string | undefined;
        "am-ET"?: string | undefined;
        "ar-AR"?: string | undefined;
        "as-IN"?: string | undefined;
        "az-AZ"?: string | undefined;
        "be-BY"?: string | undefined;
        "bg-BG"?: string | undefined;
        "bn-IN"?: string | undefined;
        "br-FR"?: string | undefined;
        "bs-BA"?: string | undefined;
        "ca-ES"?: string | undefined;
        "cb-IQ"?: string | undefined;
        "co-FR"?: string | undefined;
        "cs-CZ"?: string | undefined;
        "cx-PH"?: string | undefined;
        "cy-GB"?: string | undefined;
        "da-DK"?: string | undefined;
        de?: string | undefined;
        "de-DE"?: string | undefined;
        "el-GR"?: string | undefined;
        "en-GB"?: string | undefined;
        "en-US"?: string | undefined;
        "eo-EO"?: string | undefined;
        es?: string | undefined;
        "es-ES"?: string | undefined;
        "es-419"?: string | undefined;
        "et-EE"?: string | undefined;
        "eu-ES"?: string | undefined;
        "fa-IR"?: string | undefined;
        "ff-NG"?: string | undefined;
        "fi-FI"?: string | undefined;
        "fo-FO"?: string | undefined;
        fr?: string | undefined;
        "fr-CA"?: string | undefined;
        "fr-FR"?: string | undefined;
        "fy-NL"?: string | undefined;
        "ga-IE"?: string | undefined;
        "gl-ES"?: string | undefined;
        "gn-PY"?: string | undefined;
        "gu-IN"?: string | undefined;
        "ha-NG"?: string | undefined;
        "he-IL"?: string | undefined;
        "hi-IN"?: string | undefined;
        "hr-HR"?: string | undefined;
        "ht-HT"?: string | undefined;
        "hu-HU"?: string | undefined;
        "hy-AM"?: string | undefined;
        "id-ID"?: string | undefined;
        "ik-US"?: string | undefined;
        "is-IS"?: string | undefined;
        it?: string | undefined;
        "it-IT"?: string | undefined;
        "iu-CA"?: string | undefined;
        ja?: string | undefined;
        "ja-JP"?: string | undefined;
        "ja-KS"?: string | undefined;
        "jv-ID"?: string | undefined;
        "ka-GE"?: string | undefined;
        "kk-KZ"?: string | undefined;
        "km-KH"?: string | undefined;
        "kn-IN"?: string | undefined;
        ko?: string | undefined;
        "ko-KR"?: string | undefined;
        "ku-TR"?: string | undefined;
        "ky-KG"?: string | undefined;
        "lo-LA"?: string | undefined;
        "lt-LT"?: string | undefined;
        "lv-LV"?: string | undefined;
        "mg-MG"?: string | undefined;
        "mk-MK"?: string | undefined;
        "ml-IN"?: string | undefined;
        "mn-MN"?: string | undefined;
        "mr-IN"?: string | undefined;
        "ms-MY"?: string | undefined;
        "mt-MT"?: string | undefined;
        "my-MM"?: string | undefined;
        "nb-NO"?: string | undefined;
        "ne-NP"?: string | undefined;
        "nl-BE"?: string | undefined;
        "nl-NL"?: string | undefined;
        "nn-NO"?: string | undefined;
        "or-IN"?: string | undefined;
        "pa-IN"?: string | undefined;
        "pl-PL"?: string | undefined;
        "ps-AF"?: string | undefined;
        pt?: string | undefined;
        "pt-BR"?: string | undefined;
        "pt-PT"?: string | undefined;
        "ro-RO"?: string | undefined;
        ru?: string | undefined;
        "ru-RU"?: string | undefined;
        "rw-RW"?: string | undefined;
        "sc-IT"?: string | undefined;
        "si-LK"?: string | undefined;
        "sk-SK"?: string | undefined;
        "sl-SI"?: string | undefined;
        "sn-ZW"?: string | undefined;
        "sq-AL"?: string | undefined;
        "sr-RS"?: string | undefined;
        "sv-SE"?: string | undefined;
        "sw-KE"?: string | undefined;
        "sy-SY"?: string | undefined;
        "sz-PL"?: string | undefined;
        "ta-IN"?: string | undefined;
        "te-IN"?: string | undefined;
        "tg-TJ"?: string | undefined;
        "th-TH"?: string | undefined;
        "tl-PH"?: string | undefined;
        tr?: string | undefined;
        "tr-TR"?: string | undefined;
        "tt-RU"?: string | undefined;
        "tz-MA"?: string | undefined;
        "uk-UA"?: string | undefined;
        "ur-PK"?: string | undefined;
        "uz-UZ"?: string | undefined;
        "vi-VN"?: string | undefined;
        zh?: string | undefined;
        "zh-CN"?: string | undefined;
        "zh-HK"?: string | undefined;
        "zh-MO"?: string | undefined;
        "zh-TW"?: string | undefined;
        "zz-TR"?: string | undefined;
    };
    target: string;
    platform: import("@logto/schemas").ConnectorPlatform | null;
    logo: string;
    logoDark: string | null;
    readme: string;
}>;
export declare const postConnector: (payload: Pick<CreateConnector, 'connectorId' | 'config' | 'metadata' | 'syncProfile'>) => Promise<Connector>;
export declare const deleteConnectorById: (id: string) => Promise<unknown>;
export declare const updateConnectorConfig: (id: string, config: Record<string, unknown>, metadata?: Record<string, unknown>) => Promise<{
    isStandard?: boolean | undefined;
    configTemplate?: string | undefined;
    formItems?: ({
        placeholder?: string | undefined;
        required?: boolean | undefined;
        defaultValue?: unknown;
        showConditions?: {
            expectValue?: unknown;
            targetKey: string;
        }[] | undefined;
        description?: string | undefined;
        tooltip?: string | undefined;
        isConfidential?: boolean | undefined;
        type: import("@logto/connector-kit").ConnectorConfigFormItemType.Select;
        selectItems: {
            value: string;
            title: string;
        }[];
        key: string;
        label: string;
    } | {
        placeholder?: string | undefined;
        required?: boolean | undefined;
        defaultValue?: unknown;
        showConditions?: {
            expectValue?: unknown;
            targetKey: string;
        }[] | undefined;
        description?: string | undefined;
        tooltip?: string | undefined;
        isConfidential?: boolean | undefined;
        type: import("@logto/connector-kit").ConnectorConfigFormItemType.Text | import("@logto/connector-kit").ConnectorConfigFormItemType.Number | import("@logto/connector-kit").ConnectorConfigFormItemType.MultilineText | import("@logto/connector-kit").ConnectorConfigFormItemType.Switch | import("@logto/connector-kit").ConnectorConfigFormItemType.Json;
        key: string;
        label: string;
    })[] | undefined;
    isDemo?: boolean | undefined;
    extraInfo?: Record<string, unknown> | undefined;
    usage?: number | undefined;
    type: import("@logto/schemas").ConnectorType;
    id: string;
    name: {
        en: string;
    } & {
        "af-ZA"?: string | undefined;
        "am-ET"?: string | undefined;
        "ar-AR"?: string | undefined;
        "as-IN"?: string | undefined;
        "az-AZ"?: string | undefined;
        "be-BY"?: string | undefined;
        "bg-BG"?: string | undefined;
        "bn-IN"?: string | undefined;
        "br-FR"?: string | undefined;
        "bs-BA"?: string | undefined;
        "ca-ES"?: string | undefined;
        "cb-IQ"?: string | undefined;
        "co-FR"?: string | undefined;
        "cs-CZ"?: string | undefined;
        "cx-PH"?: string | undefined;
        "cy-GB"?: string | undefined;
        "da-DK"?: string | undefined;
        de?: string | undefined;
        "de-DE"?: string | undefined;
        "el-GR"?: string | undefined;
        "en-GB"?: string | undefined;
        "en-US"?: string | undefined;
        "eo-EO"?: string | undefined;
        es?: string | undefined;
        "es-ES"?: string | undefined;
        "es-419"?: string | undefined;
        "et-EE"?: string | undefined;
        "eu-ES"?: string | undefined;
        "fa-IR"?: string | undefined;
        "ff-NG"?: string | undefined;
        "fi-FI"?: string | undefined;
        "fo-FO"?: string | undefined;
        fr?: string | undefined;
        "fr-CA"?: string | undefined;
        "fr-FR"?: string | undefined;
        "fy-NL"?: string | undefined;
        "ga-IE"?: string | undefined;
        "gl-ES"?: string | undefined;
        "gn-PY"?: string | undefined;
        "gu-IN"?: string | undefined;
        "ha-NG"?: string | undefined;
        "he-IL"?: string | undefined;
        "hi-IN"?: string | undefined;
        "hr-HR"?: string | undefined;
        "ht-HT"?: string | undefined;
        "hu-HU"?: string | undefined;
        "hy-AM"?: string | undefined;
        "id-ID"?: string | undefined;
        "ik-US"?: string | undefined;
        "is-IS"?: string | undefined;
        it?: string | undefined;
        "it-IT"?: string | undefined;
        "iu-CA"?: string | undefined;
        ja?: string | undefined;
        "ja-JP"?: string | undefined;
        "ja-KS"?: string | undefined;
        "jv-ID"?: string | undefined;
        "ka-GE"?: string | undefined;
        "kk-KZ"?: string | undefined;
        "km-KH"?: string | undefined;
        "kn-IN"?: string | undefined;
        ko?: string | undefined;
        "ko-KR"?: string | undefined;
        "ku-TR"?: string | undefined;
        "ky-KG"?: string | undefined;
        "lo-LA"?: string | undefined;
        "lt-LT"?: string | undefined;
        "lv-LV"?: string | undefined;
        "mg-MG"?: string | undefined;
        "mk-MK"?: string | undefined;
        "ml-IN"?: string | undefined;
        "mn-MN"?: string | undefined;
        "mr-IN"?: string | undefined;
        "ms-MY"?: string | undefined;
        "mt-MT"?: string | undefined;
        "my-MM"?: string | undefined;
        "nb-NO"?: string | undefined;
        "ne-NP"?: string | undefined;
        "nl-BE"?: string | undefined;
        "nl-NL"?: string | undefined;
        "nn-NO"?: string | undefined;
        "or-IN"?: string | undefined;
        "pa-IN"?: string | undefined;
        "pl-PL"?: string | undefined;
        "ps-AF"?: string | undefined;
        pt?: string | undefined;
        "pt-BR"?: string | undefined;
        "pt-PT"?: string | undefined;
        "ro-RO"?: string | undefined;
        ru?: string | undefined;
        "ru-RU"?: string | undefined;
        "rw-RW"?: string | undefined;
        "sc-IT"?: string | undefined;
        "si-LK"?: string | undefined;
        "sk-SK"?: string | undefined;
        "sl-SI"?: string | undefined;
        "sn-ZW"?: string | undefined;
        "sq-AL"?: string | undefined;
        "sr-RS"?: string | undefined;
        "sv-SE"?: string | undefined;
        "sw-KE"?: string | undefined;
        "sy-SY"?: string | undefined;
        "sz-PL"?: string | undefined;
        "ta-IN"?: string | undefined;
        "te-IN"?: string | undefined;
        "tg-TJ"?: string | undefined;
        "th-TH"?: string | undefined;
        "tl-PH"?: string | undefined;
        tr?: string | undefined;
        "tr-TR"?: string | undefined;
        "tt-RU"?: string | undefined;
        "tz-MA"?: string | undefined;
        "uk-UA"?: string | undefined;
        "ur-PK"?: string | undefined;
        "uz-UZ"?: string | undefined;
        "vi-VN"?: string | undefined;
        zh?: string | undefined;
        "zh-CN"?: string | undefined;
        "zh-HK"?: string | undefined;
        "zh-MO"?: string | undefined;
        "zh-TW"?: string | undefined;
        "zz-TR"?: string | undefined;
    };
    description: {
        en: string;
    } & {
        "af-ZA"?: string | undefined;
        "am-ET"?: string | undefined;
        "ar-AR"?: string | undefined;
        "as-IN"?: string | undefined;
        "az-AZ"?: string | undefined;
        "be-BY"?: string | undefined;
        "bg-BG"?: string | undefined;
        "bn-IN"?: string | undefined;
        "br-FR"?: string | undefined;
        "bs-BA"?: string | undefined;
        "ca-ES"?: string | undefined;
        "cb-IQ"?: string | undefined;
        "co-FR"?: string | undefined;
        "cs-CZ"?: string | undefined;
        "cx-PH"?: string | undefined;
        "cy-GB"?: string | undefined;
        "da-DK"?: string | undefined;
        de?: string | undefined;
        "de-DE"?: string | undefined;
        "el-GR"?: string | undefined;
        "en-GB"?: string | undefined;
        "en-US"?: string | undefined;
        "eo-EO"?: string | undefined;
        es?: string | undefined;
        "es-ES"?: string | undefined;
        "es-419"?: string | undefined;
        "et-EE"?: string | undefined;
        "eu-ES"?: string | undefined;
        "fa-IR"?: string | undefined;
        "ff-NG"?: string | undefined;
        "fi-FI"?: string | undefined;
        "fo-FO"?: string | undefined;
        fr?: string | undefined;
        "fr-CA"?: string | undefined;
        "fr-FR"?: string | undefined;
        "fy-NL"?: string | undefined;
        "ga-IE"?: string | undefined;
        "gl-ES"?: string | undefined;
        "gn-PY"?: string | undefined;
        "gu-IN"?: string | undefined;
        "ha-NG"?: string | undefined;
        "he-IL"?: string | undefined;
        "hi-IN"?: string | undefined;
        "hr-HR"?: string | undefined;
        "ht-HT"?: string | undefined;
        "hu-HU"?: string | undefined;
        "hy-AM"?: string | undefined;
        "id-ID"?: string | undefined;
        "ik-US"?: string | undefined;
        "is-IS"?: string | undefined;
        it?: string | undefined;
        "it-IT"?: string | undefined;
        "iu-CA"?: string | undefined;
        ja?: string | undefined;
        "ja-JP"?: string | undefined;
        "ja-KS"?: string | undefined;
        "jv-ID"?: string | undefined;
        "ka-GE"?: string | undefined;
        "kk-KZ"?: string | undefined;
        "km-KH"?: string | undefined;
        "kn-IN"?: string | undefined;
        ko?: string | undefined;
        "ko-KR"?: string | undefined;
        "ku-TR"?: string | undefined;
        "ky-KG"?: string | undefined;
        "lo-LA"?: string | undefined;
        "lt-LT"?: string | undefined;
        "lv-LV"?: string | undefined;
        "mg-MG"?: string | undefined;
        "mk-MK"?: string | undefined;
        "ml-IN"?: string | undefined;
        "mn-MN"?: string | undefined;
        "mr-IN"?: string | undefined;
        "ms-MY"?: string | undefined;
        "mt-MT"?: string | undefined;
        "my-MM"?: string | undefined;
        "nb-NO"?: string | undefined;
        "ne-NP"?: string | undefined;
        "nl-BE"?: string | undefined;
        "nl-NL"?: string | undefined;
        "nn-NO"?: string | undefined;
        "or-IN"?: string | undefined;
        "pa-IN"?: string | undefined;
        "pl-PL"?: string | undefined;
        "ps-AF"?: string | undefined;
        pt?: string | undefined;
        "pt-BR"?: string | undefined;
        "pt-PT"?: string | undefined;
        "ro-RO"?: string | undefined;
        ru?: string | undefined;
        "ru-RU"?: string | undefined;
        "rw-RW"?: string | undefined;
        "sc-IT"?: string | undefined;
        "si-LK"?: string | undefined;
        "sk-SK"?: string | undefined;
        "sl-SI"?: string | undefined;
        "sn-ZW"?: string | undefined;
        "sq-AL"?: string | undefined;
        "sr-RS"?: string | undefined;
        "sv-SE"?: string | undefined;
        "sw-KE"?: string | undefined;
        "sy-SY"?: string | undefined;
        "sz-PL"?: string | undefined;
        "ta-IN"?: string | undefined;
        "te-IN"?: string | undefined;
        "tg-TJ"?: string | undefined;
        "th-TH"?: string | undefined;
        "tl-PH"?: string | undefined;
        tr?: string | undefined;
        "tr-TR"?: string | undefined;
        "tt-RU"?: string | undefined;
        "tz-MA"?: string | undefined;
        "uk-UA"?: string | undefined;
        "ur-PK"?: string | undefined;
        "uz-UZ"?: string | undefined;
        "vi-VN"?: string | undefined;
        zh?: string | undefined;
        "zh-CN"?: string | undefined;
        "zh-HK"?: string | undefined;
        "zh-MO"?: string | undefined;
        "zh-TW"?: string | undefined;
        "zz-TR"?: string | undefined;
    };
    syncProfile: boolean;
    connectorId: string;
    config: import("@logto/schemas").JsonObject;
    metadata: {
        [x: string]: unknown;
        target?: string | undefined;
        name?: ({
            en: string;
        } & {
            "af-ZA"?: string | undefined;
            "am-ET"?: string | undefined;
            "ar-AR"?: string | undefined;
            "as-IN"?: string | undefined;
            "az-AZ"?: string | undefined;
            "be-BY"?: string | undefined;
            "bg-BG"?: string | undefined;
            "bn-IN"?: string | undefined;
            "br-FR"?: string | undefined;
            "bs-BA"?: string | undefined;
            "ca-ES"?: string | undefined;
            "cb-IQ"?: string | undefined;
            "co-FR"?: string | undefined;
            "cs-CZ"?: string | undefined;
            "cx-PH"?: string | undefined;
            "cy-GB"?: string | undefined;
            "da-DK"?: string | undefined;
            de?: string | undefined;
            "de-DE"?: string | undefined;
            "el-GR"?: string | undefined;
            "en-GB"?: string | undefined;
            "en-US"?: string | undefined;
            "eo-EO"?: string | undefined;
            es?: string | undefined;
            "es-ES"?: string | undefined;
            "es-419"?: string | undefined;
            "et-EE"?: string | undefined;
            "eu-ES"?: string | undefined;
            "fa-IR"?: string | undefined;
            "ff-NG"?: string | undefined;
            "fi-FI"?: string | undefined;
            "fo-FO"?: string | undefined;
            fr?: string | undefined;
            "fr-CA"?: string | undefined;
            "fr-FR"?: string | undefined;
            "fy-NL"?: string | undefined;
            "ga-IE"?: string | undefined;
            "gl-ES"?: string | undefined;
            "gn-PY"?: string | undefined;
            "gu-IN"?: string | undefined;
            "ha-NG"?: string | undefined;
            "he-IL"?: string | undefined;
            "hi-IN"?: string | undefined;
            "hr-HR"?: string | undefined;
            "ht-HT"?: string | undefined;
            "hu-HU"?: string | undefined;
            "hy-AM"?: string | undefined;
            "id-ID"?: string | undefined;
            "ik-US"?: string | undefined;
            "is-IS"?: string | undefined;
            it?: string | undefined;
            "it-IT"?: string | undefined;
            "iu-CA"?: string | undefined;
            ja?: string | undefined;
            "ja-JP"?: string | undefined;
            "ja-KS"?: string | undefined;
            "jv-ID"?: string | undefined;
            "ka-GE"?: string | undefined;
            "kk-KZ"?: string | undefined;
            "km-KH"?: string | undefined;
            "kn-IN"?: string | undefined;
            ko?: string | undefined;
            "ko-KR"?: string | undefined;
            "ku-TR"?: string | undefined;
            "ky-KG"?: string | undefined;
            "lo-LA"?: string | undefined;
            "lt-LT"?: string | undefined;
            "lv-LV"?: string | undefined;
            "mg-MG"?: string | undefined;
            "mk-MK"?: string | undefined;
            "ml-IN"?: string | undefined;
            "mn-MN"?: string | undefined;
            "mr-IN"?: string | undefined;
            "ms-MY"?: string | undefined;
            "mt-MT"?: string | undefined;
            "my-MM"?: string | undefined;
            "nb-NO"?: string | undefined;
            "ne-NP"?: string | undefined;
            "nl-BE"?: string | undefined;
            "nl-NL"?: string | undefined;
            "nn-NO"?: string | undefined;
            "or-IN"?: string | undefined;
            "pa-IN"?: string | undefined;
            "pl-PL"?: string | undefined;
            "ps-AF"?: string | undefined;
            pt?: string | undefined;
            "pt-BR"?: string | undefined;
            "pt-PT"?: string | undefined;
            "ro-RO"?: string | undefined;
            ru?: string | undefined;
            "ru-RU"?: string | undefined;
            "rw-RW"?: string | undefined;
            "sc-IT"?: string | undefined;
            "si-LK"?: string | undefined;
            "sk-SK"?: string | undefined;
            "sl-SI"?: string | undefined;
            "sn-ZW"?: string | undefined;
            "sq-AL"?: string | undefined;
            "sr-RS"?: string | undefined;
            "sv-SE"?: string | undefined;
            "sw-KE"?: string | undefined;
            "sy-SY"?: string | undefined;
            "sz-PL"?: string | undefined;
            "ta-IN"?: string | undefined;
            "te-IN"?: string | undefined;
            "tg-TJ"?: string | undefined;
            "th-TH"?: string | undefined;
            "tl-PH"?: string | undefined;
            tr?: string | undefined;
            "tr-TR"?: string | undefined;
            "tt-RU"?: string | undefined;
            "tz-MA"?: string | undefined;
            "uk-UA"?: string | undefined;
            "ur-PK"?: string | undefined;
            "uz-UZ"?: string | undefined;
            "vi-VN"?: string | undefined;
            zh?: string | undefined;
            "zh-CN"?: string | undefined;
            "zh-HK"?: string | undefined;
            "zh-MO"?: string | undefined;
            "zh-TW"?: string | undefined;
            "zz-TR"?: string | undefined;
        }) | undefined;
        logo?: string | undefined;
        logoDark?: string | null | undefined;
    };
    target: string;
    platform: import("@logto/schemas").ConnectorPlatform | null;
    logo: string;
    logoDark: string | null;
    readme: string;
}>;
export declare const sendSmsTestMessage: (connectorFactoryId: string, phone: string, config: Record<string, unknown>) => Promise<import("got").Response<string>>;
export declare const sendEmailTestMessage: (connectorFactoryId: string, email: string, config: Record<string, unknown>) => Promise<import("got").Response<string>>;
export declare const getConnectorAuthorizationUri: (connectorId: string, state: string, redirectUri: string) => Promise<{
    redirectTo: string;
}>;
